import { defineLocaleResource } from "./define-locale-resource";

export const workViews = defineLocaleResource({
  "zh-TW": {
    allRepositories: "所有儲存庫", allAssignees: "所有負責人", closed: "已關閉", currentAssignee: "目前負責人", lastAssignee: "最後負責人", noLastAssignee: "未記錄", currentUserAssignee: "目前使用者{{login}}", currentUserUnavailable: "無法取得目前使用者", dateAnomalies: "日期異常", ganttLabel: "甘特圖", issueState: "問題狀態", loadingCurrentUserIssues: "正在載入目前使用者的問題…", noFilteredIssues: "沒有符合條件的問題", noUnscheduledIssues: "沒有未排程的問題", noReadableRepositories: "目前沒有可讀取的 Repository。", noAssignee: "未指派", open: "未關閉", scheduledIssues: "已排程問題", unscheduled: "未排程", ganttDescription: "依負責人與日期檢視所有可讀 Repository 的工作。", ganttEyebrow: "所有儲存庫・甘特圖", kanbanDescription: "依 Issue Status 檢視所有可讀 Repository 的問題。", kanbanEyebrow: "所有儲存庫看板", statusColumn: "狀態欄", transitionRejected: "狀態變更未完成", viewLoadError: "工作檢視無法載入", retry: "重試", labels: "標籤", moveIssueToStatus: "將 {{title}} 移至狀態", moveToStatus: "移至狀態", selectColumn: "選擇狀態", nextAction: "下一步：{{action}}", scheduleDateInvalid: "排程日期異常", unassigned: "未指派", ganttViewOptions: "甘特圖欄位設定", ganttVisibleColumns: "顯示欄位", ganttVisibleColumnsHelp: "標題、負責人與狀態固定顯示；其他欄位可選擇顯示。", ganttFixedColumn: "固定顯示", ganttSaveColumnOrder: "儲存為預設欄序", ganttRestoreColumnDefaults: "還原預設欄位", ganttColumnMoveHelp: "按空白鍵選取欄位，再用左右方向鍵移動；再次按空白鍵確認，Escape 取消。", ganttColumnMoved: "{{column}} 已移至第 {{position}} 欄", ganttStartDate: "時間軸起始日", today: "今天", scale: "刻度", scaleDay: "日", scaleWeek: "週", scaleTwoWeeks: "兩週", scaleMonth: "月", timeline: "時間軸", monthHeader: "月份", dateHeader: "日期", weekend: "週末", todayMarker: "今天", noTimelineDates: "目前沒有可顯示的排程日期",
  },
  en: {
    allRepositories: "All repos", allAssignees: "All assignees", closed: "Closed", currentAssignee: "Current assignee", lastAssignee: "Last assignee", noLastAssignee: "Not recorded", currentUserAssignee: "Current user{{login}}", currentUserUnavailable: "Could not load the current user", dateAnomalies: "Date anomalies", ganttLabel: "Gantt Chart", issueState: "Issue state", loadingCurrentUserIssues: "Loading the current user's issues…", noFilteredIssues: "No issues match these filters", noUnscheduledIssues: "No unscheduled issues", noReadableRepositories: "No readable repositories are available.", noAssignee: "Unassigned", open: "Open", scheduledIssues: "Scheduled issues", unscheduled: "Unscheduled", ganttDescription: "View work across every readable repository by owner and date.", ganttEyebrow: "All repos · Gantt Chart", kanbanDescription: "View issues across every readable repository by Status.", kanbanEyebrow: "ALL REPOS KANBAN", statusColumn: "Status column", transitionRejected: "The Status change was not completed", viewLoadError: "Could not load this work view", retry: "Retry", labels: "Labels", moveIssueToStatus: "Move {{title}} to Status", moveToStatus: "Move to Status", selectColumn: "Select a Status", nextAction: "Next: {{action}}", scheduleDateInvalid: "Schedule date anomaly", unassigned: "Unassigned", ganttViewOptions: "Gantt Chart columns", ganttVisibleColumns: "Visible columns", ganttVisibleColumnsHelp: "Title, Assignee, and Status are always shown. Choose which other columns to display.", ganttFixedColumn: "Always shown", ganttSaveColumnOrder: "Save as default order", ganttRestoreColumnDefaults: "Restore default columns", ganttColumnMoveHelp: "Press Space to pick up a column, use the arrow keys to move it, then press Space again. Escape cancels.", ganttColumnMoved: "{{column}} moved to column {{position}}", ganttStartDate: "Timeline start date", today: "Today", scale: "Scale", scaleDay: "Day", scaleWeek: "Week", scaleTwoWeeks: "2 weeks", scaleMonth: "Month", timeline: "Timeline", monthHeader: "Month", dateHeader: "Date", weekend: "Weekend", todayMarker: "Today", noTimelineDates: "No scheduled dates to display",
  },
  ja: {
    allRepositories: "すべてのリポジトリ", allAssignees: "すべての担当者", closed: "クローズ済み", currentAssignee: "現在の担当者", lastAssignee: "最後の担当者", noLastAssignee: "記録なし", currentUserAssignee: "現在のユーザー{{login}}", currentUserUnavailable: "現在のユーザーを取得できません", dateAnomalies: "日付の異常", ganttLabel: "ガントチャート", issueState: "課題の状態", loadingCurrentUserIssues: "現在のユーザーの課題を読み込み中…", noFilteredIssues: "条件に一致する課題はありません", noUnscheduledIssues: "未スケジュールの課題はありません", noReadableRepositories: "読み取り可能なリポジトリはありません。", noAssignee: "未割り当て", open: "オープン", scheduledIssues: "スケジュール済み課題", unscheduled: "未スケジュール", ganttDescription: "読み取り可能なすべてのリポジトリの作業を担当者と日付で表示します。", ganttEyebrow: "すべてのリポジトリ・ガントチャート", kanbanDescription: "読み取り可能なすべてのリポジトリの課題を Status で表示します。", kanbanEyebrow: "すべてのリポジトリ カンバン", statusColumn: "ステータス列", transitionRejected: "Status を変更できませんでした", viewLoadError: "作業ビューを読み込めませんでした", retry: "再試行", labels: "ラベル", moveIssueToStatus: "{{title}} をステータスに移動", moveToStatus: "ステータスを変更", selectColumn: "ステータスを選択", nextAction: "次の操作：{{action}}", scheduleDateInvalid: "スケジュール日の異常", unassigned: "未割り当て", ganttViewOptions: "ガントチャートの列", ganttVisibleColumns: "表示する列", ganttVisibleColumnsHelp: "タイトル、担当者、状態は常に表示されます。他の列は表示を選択できます。", ganttFixedColumn: "常に表示", ganttSaveColumnOrder: "既定の列順として保存", ganttRestoreColumnDefaults: "既定の列に戻す", ganttColumnMoveHelp: "Space キーで列を選び、左右キーで移動してから再度 Space キーで確定します。Escape でキャンセルします。", ganttColumnMoved: "{{column}} を {{position}} 列目に移動しました", ganttStartDate: "タイムラインの開始日", today: "今日", scale: "表示単位", scaleDay: "日", scaleWeek: "週", scaleTwoWeeks: "2週間", scaleMonth: "月", timeline: "タイムライン", monthHeader: "月", dateHeader: "日付", weekend: "週末", todayMarker: "今日", noTimelineDates: "表示できるスケジュール日がありません",
  },
});
