import { defineLocaleResource } from "./define-locale-resource";

export const workViews = defineLocaleResource({
  "zh-TW": {
    allRepositories: "所有儲存庫", allAssignees: "所有負責人", closed: "已關閉", currentAssignee: "目前負責人", currentUserAssignee: "目前使用者{{login}}", currentUserUnavailable: "無法取得目前使用者", dateAnomalies: "日期異常", ganttLabel: "Gantt 圖", issueState: "問題狀態", loadingCurrentUserIssues: "正在載入目前使用者的問題…", noFilteredIssues: "沒有符合條件的問題", noUnscheduledIssues: "沒有未排程問題", noReadableRepositories: "目前沒有可讀取的 Repository。", noAssignee: "未指派", open: "未關閉", scheduledIssues: "已排程問題", unscheduled: "未排程", ganttDescription: "依負責人與日期檢視所有可讀 Repository 的工作。", ganttEyebrow: "所有儲存庫 Gantt 圖", kanbanDescription: "依工作流程檢視所有可讀 Repository 的問題。", kanbanEyebrow: "所有儲存庫 Kanban", statusColumn: "狀態欄", transitionRejected: "狀態變更未完成", viewLoadError: "工作檢視無法載入", retry: "重試", labels: "標籤", moveIssueToStatus: "將 {{title}} 移至狀態", moveToStatus: "移至狀態", selectColumn: "選擇狀態", nextAction: "下一步：{{action}}", scheduleDateInvalid: "排程日期異常", unassigned: "未指派",
  },
  en: {
    allRepositories: "All repos", allAssignees: "All assignees", closed: "Closed", currentAssignee: "Current assignee", currentUserAssignee: "Current user{{login}}", currentUserUnavailable: "Could not load the current user", dateAnomalies: "Date anomalies", ganttLabel: "Gantt chart", issueState: "Issue state", loadingCurrentUserIssues: "Loading the current user's issues…", noFilteredIssues: "No issues match these filters", noUnscheduledIssues: "No unscheduled issues", noReadableRepositories: "No readable repositories are available.", noAssignee: "Unassigned", open: "Open", scheduledIssues: "Scheduled issues", unscheduled: "Unscheduled", ganttDescription: "View work across every readable repository by owner and date.", ganttEyebrow: "ALL REPOS GANTT", kanbanDescription: "View issues across every readable repository by workflow.", kanbanEyebrow: "ALL REPOS KANBAN", statusColumn: "Status column", transitionRejected: "The workflow transition was not completed", viewLoadError: "Could not load this work view", retry: "Retry", labels: "Labels", moveIssueToStatus: "Move {{title}} to status", moveToStatus: "Move to status", selectColumn: "Select a status", nextAction: "Next: {{action}}", scheduleDateInvalid: "Schedule date anomaly", unassigned: "Unassigned",
  },
  ja: {
    allRepositories: "すべてのリポジトリ", allAssignees: "すべての担当者", closed: "クローズ済み", currentAssignee: "現在の担当者", currentUserAssignee: "現在のユーザー{{login}}", currentUserUnavailable: "現在のユーザーを取得できません", dateAnomalies: "日付の異常", ganttLabel: "ガントチャート", issueState: "課題の状態", loadingCurrentUserIssues: "現在のユーザーの課題を読み込み中…", noFilteredIssues: "条件に一致する課題はありません", noUnscheduledIssues: "未スケジュールの課題はありません", noReadableRepositories: "読み取り可能なリポジトリはありません。", noAssignee: "未割り当て", open: "オープン", scheduledIssues: "スケジュール済み課題", unscheduled: "未スケジュール", ganttDescription: "読み取り可能なすべてのリポジトリの作業を担当者と日付で表示します。", ganttEyebrow: "すべてのリポジトリ ガントチャート", kanbanDescription: "読み取り可能なすべてのリポジトリの課題をワークフローで表示します。", kanbanEyebrow: "すべてのリポジトリ カンバン", statusColumn: "ステータス列", transitionRejected: "ワークフローを変更できませんでした", viewLoadError: "作業ビューを読み込めませんでした", retry: "再試行", labels: "ラベル", moveIssueToStatus: "{{title}} をステータスに移動", moveToStatus: "ステータスを変更", selectColumn: "ステータスを選択", nextAction: "次の操作：{{action}}", scheduleDateInvalid: "スケジュール日の異常", unassigned: "未割り当て",
  },
});
